name: Build Fireworks Simulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Fireworks.sln

      - name: Build
        run: dotnet build Fireworks.sln --configuration Release --no-restore

      - name: Publish build
        run: dotnet publish FireworksSimulator/FireworksSimulator.csproj --configuration Release --output ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-release
          path: ./publish
